spring.application.name=mcp-test
spring.main.banner-mode=off
spring.threads.virtual.enabled=true

#MCP Server configuration
spring.ai.mcp.server.name=moses-mcp-test
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.type=sync

spring.ai.tools.observations.include-content=true
spring.ai.tools.observations.include-metadata=true
spring.ai.tools.observations.include-messages=true
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true

logging.level.de.mosesonline.mcptest.mcptest=DEBUG
